import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/AuthProvider";
import QueryClientProvider from "./api/QueryClientProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by Emmanuel, the developer",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.variable} antialiased`}>
          <QueryClientProvider>
            <Theme accentColor="cyan" panelBackground="solid" scaling="110%">
              <NavBar />
              <main>{children}</main>
            </Theme>
          </QueryClientProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
